### ISSUE TITLE
Exception in train unet

### ISSUE THREAD

**Issue by asmagen** [yapic/yapic#15]
Any insight into this problem?
```
user$ yapic train unet_2d "cropped_masked.png" pixel_classifier_ilastik.ilp -e 500 --gpu=0
Using TensorFlow backend.
/Users/Assaf/Dropbox/shared_imaging/cropped_masked.png
/Users/Assaf/Dropbox/shared_imaging/pixel_classifier_ilastik.ilp
/usr/local/lib/python3.7/site-packages/pyilastik/ilastik_storage_version_01.py:270: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  labels[s_fmt] = self.load_block_data(item_index, i)
/usr/local/lib/python3.7/site-packages/pyilastik/ilastik_storage_version_01.py:307: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  labels_q[q_slice] = labels_p[p_slice]
tile size zxy: (1, 572, 572)
ValueError: 35152 is not a valid Endian

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/yapic", line 8, in <module>
    sys.exit(entry_point())
  File "/usr/local/lib/python3.7/site-packages/yapic/main.py", line 122, in entry_point
    res = main(arguments)
  File "/usr/local/lib/python3.7/site-packages/yapic/main.py", line 98, in main
    s.make_model(model_name, (size_z, size_xy, size_xy))
  File "/usr/local/lib/python3.7/site-packages/yapic/session.py", line 91, in make_model
    nr_channels = self.dataset.image_dimensions(0)[0]
  File "/usr/local/lib/python3.7/site-packages/yapic_io/dataset.py", line 71, in image_dimensions
    return self.pixel_connector.image_dimensions(image_nr)
  File "/usr/local/lib/python3.7/site-packages/yapic_io/tiff_connector.py", line 286, in image_dimensions
    img = self._open_image_file(image_nr)
  File "/usr/local/lib/python3.7/site-packages/yapic_io/tiff_connector.py", line 282, in _open_image_file
    return Tiff.memmap_tcz(path)
  File "/usr/local/lib/python3.7/site-packages/bigtiff/tiff.py", line 40, in memmap_tcz
    slices = [s for s in cls.from_fd(fd)]
  File "/usr/local/lib/python3.7/site-packages/bigtiff/tiff.py", line 35, in from_fd
    return cls(KaitaiStream(fd))
  File "/usr/local/lib/python3.7/site-packages/bigtiff/tif_format.py", line 137, in __init__
    self._read()
  File "/usr/local/lib/python3.7/site-packages/bigtiff/tif_format.py", line 140, in _read
    self.endian = self._root.Endian(self._io.read_u2be())
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 564, in __new__
    raise exc
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 548, in __new__
    result = cls._missing_(value)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 577, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 35152 is not a valid Endian
```

**Comment by cmohl2013** [comment]
Hi @asmagen ,

png format is not supported. Please open your png in [Fiji](https://fiji.sc/), and save as tif. This should work, without changing the ilastik file.

**Comment by asmagen** [comment]
I'm trying to do the pipeline work computationally and not manually with opening files in Fiji and storing them in a different format etc. I just used tiff.imsave to save the png as a tiff or tif file but not I get this error:
```
Using TensorFlow backend.
/Users/Assaf/Dropbox/shared_imaging/tiles/cropped_img.tif
/Users/Assaf/Dropbox/shared_imaging/CD3_pixel_classifier.ilp
/usr/local/lib/python3.7/site-packages/pyilastik/ilastik_storage_version_01.py:270: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  labels[s_fmt] = self.load_block_data(item_index, i)
/usr/local/lib/python3.7/site-packages/pyilastik/ilastik_storage_version_01.py:307: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  labels_q[q_slice] = labels_p[p_slice]
tile size zxy: (1, 572, 572)
nr_channels: 3
Traceback (most recent call last):
  File "/usr/local/bin/yapic", line 8, in <module>
    sys.exit(entry_point())
  File "/usr/local/lib/python3.7/site-packages/yapic/main.py", line 122, in entry_point
    res = main(arguments)
  File "/usr/local/lib/python3.7/site-packages/yapic/main.py", line 98, in main
    s.make_model(model_name, (size_z, size_xy, size_xy))
  File "/usr/local/lib/python3.7/site-packages/yapic/session.py", line 96, in make_model
    self.model = make_model(model_name, n_classes, input_size_czxy)
  File "/usr/local/lib/python3.7/site-packages/yapic/network.py", line 68, in make_model
    net = setup_network(network_name, N_classes, input_size_czxy)
  File "/usr/local/lib/python3.7/site-packages/yapic/network.py", line 23, in setup_network
    network = network_module.build_network(N_classes, input_size_czxy)
  File "/usr/local/lib/python3.7/site-packages/yapic/networks/unet_2d.py", line 64, in build_network
    assert N_classes >= 2
AssertionError
```
