### ISSUE TITLE
TensorFlow versions

### ISSUE THREAD

**Issue by lacan** [yapic/yapic#22]
Hello, I have a model that I created on a cluster, but their installation only allows for TF2.3 

For training, this works and I get no problems and a model.h5 is output.

However, creating a TF 1.15 environment to export the model does not work:

`yapic deploy model.h5 leaves_example_data/leaves_1.tif demo_model --skip-predict`
Yields
Traceback (most recent call last):
  File "/home/oburri/env-yapic/bin/yapic", line 8, in <module>
    sys.exit(entry_point())
  File "/home/oburri/env-yapic/lib/python3.7/site-packages/yapic/main.py", line 176, in entry_point
    res = main(arguments)
  File "/home/oburri/env-yapic/lib/python3.7/site-packages/yapic/main.py", line 116, in main
    applymodel=predict_example_image)
  File "/home/oburri/env-yapic/lib/python3.7/site-packages/yapic/deepimagej_exporter.py", line 68, in export_as_deepimagej
    self._export_as_tensorflow_model()
  File "/home/oburri/env-yapic/lib/python3.7/site-packages/yapic/deepimagej_exporter.py", line 214, in _export_as_tensorflow_model
    builder = tf.saved_model.builder.SavedModelBuilder(self.save_path)
AttributeError: module 'tensorflow._api.v2.saved_model' has no attribute 'builder'

Question: Is this linked to the TF version when training? i cannot install TF 2.1 on the cluster because the right CUDNN and CUDA libraries are not currently installed on the nodes. Would it be possible to get this working? ie. Train on TF 2.3 and export on TF1.15?

Best

Oli

**Comment by cmohl2013** [comment]
I do not know, since we have never tested with TF 2.3. 
I know the problem with following setup: training in TF 2.1  and exporting in TF 1.13. For the combination TF2.1 and TF1.15 it works, at least in our test setup. 

The problem is: We use a custom loss function (to deal with sparse labels we can not use the default categorical crossentropy). The custom loss function is stored with the model in the h5 file. There seem to be incompatibilities, regarding on the specific TF version combination, i.e. loss functions exported with Keras backend of TF2.3 can not be imported with Keras backend of TF1.15.

I do not have a good idea how to deal with that problem. If future versions of DeepIamgeJ may support TF2, this problem may be solved.

**Comment by esgomezm** [comment]
If it helps, DeepImageJ (and in general, the TF - Java connection) supports models until TF 2.2 thanks to its backward compatibility. Here the 'problem' is with TF 2.3, not only with the java connection but also in python. While you can load trained TF 1.15 models in TF 2.3, it is not possible the other way around. The good news is that TF is working on the release for the java connection with TF2.3
