### ISSUE TITLE
Memory-mapping not working for tifffile memmap

### ISSUE THREAD

**Issue by pranjaldhole** [yapic/yapic#54]
Tiff_connector now uses `memmap` from `tifffile` instead of `Bigtiff` package which was disconnected from repo to make yapic work cross-platform. This behaviour now fails when label files are `.tif` files instead of `.h5` file from napari.
The error log reads as follows:
```bash
Traceback (most recent call last):
  File "/home/dholep/venvs/yapic_test/bin/yapic", line 33, in <module>
    sys.exit(load_entry_point('yapic', 'console_scripts', 'yapic')())
  File "/home/dholep/projects/yapic/yapic/main.py", line 187, in entry_point
    res = main(arguments)
  File "/home/dholep/projects/yapic/yapic/main.py", line 139, in main
    s.load_training_data(image_path, label_path, batch_size)
  File "/home/dholep/projects/yapic/yapic/session.py", line 61, in load_training_data
    _connector = io_connector(image_path, label_path)
  File "/home/dholep/venvs/yapic_test/lib/python3.8/site-packages/yapic_io/connector.py", line 39, in io_connector
    return TiffConnector(image_path, label_path, *args, **kwds)
  File "/home/dholep/venvs/yapic_test/lib/python3.8/site-packages/yapic_io/tiff_connector.py", line 136, in __init__
    original_labels = self.original_label_values_for_all_images()
  File "/home/dholep/venvs/yapic_test/lib/python3.8/site-packages/yapic_io/tiff_connector.py", line 531, in original_label_values_for_all_images
    slices = self._open_label_file(image_nr)
  File "/home/dholep/venvs/yapic_test/lib/python3.8/site-packages/yapic_io/tiff_connector.py", line 473, in _open_label_file
    lbl_data = memmap(path)
  File "/home/dholep/venvs/yapic_test/lib/python3.8/site-packages/tifffile/tifffile.py", line 1044, in memmap
    raise ValueError('image data are not memory-mappable')
ValueError: image data are not memory-mappable
```

## To Do:

- Check whether `tifffile` based `memmap` can be used for yapic while parsing label files as `.tif` files.
- If not, reinstate `bigtiff` based `memmap` function.

**Comment by cmohl2013** [comment]
Hi @pranjaldhole yes I will do that.

**Comment by dlesmesl** [comment]
I will take it a look, could you please share the `.tif` file to reproduce the error?

On the other hand, maybe this could be helpful https://github.com/cgohlke/tifffile/issues/52
There, they said:

"In case you are referring to memory-mapping the image data in the file as a numpy array. It depends on how the file was written. If all the image data was written contiguously, without any compression, tiling, predictors, packing, etc, then tifffile.memmap can return a memory mapped numpy array"

**Comment by pranjaldhole** [comment]
@dlesmesl  I put a zip file with stacked leaves we worked on when we were building the plugins here: https://github.com/yapic/yapic/issues/54#issuecomment-1056660710

**Comment by cmohl2013** [comment]
@dlesmesl thank you for having a look at that, i have not managed so far. If you can reproduce the error, I would first open the label file in fiji and then save as tif again and see if the error is still present.
